- name: Make sure unattended-upgrades package is installed
  apt: pkg=unattended-upgrades state=installed

- name: Run unattended-upgrades once
  shell: unattended-upgrades -d

- name: Unattended upgrades should be run periodically
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
  with_items:
    - 10periodic
    - 50unattended-upgrades
  
