---
- name: create a security group to open ports 80 and 22
  ec2_group:
    name: "{{ security_group_name }}"
    description: "{{ security_group_description }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

- name: create instance
  ec2:
    region: "{{ region }}"
    key_name: "{{ ssh_key_name }}"
    group: "{{ security_group_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: yes
    exact_count: 1
    count_tag:
      Name: "{{ instance_tags.Name }}"
    instance_tags: "{{ instance_tags }}"
  register: ec2

- name: add instance to host group
  add_host:
    hostname="{{ item.public_ip }}"
    ansible_ssh_private_key_file="{{ ssh_key_private }}"
    groupname="web_servers"
  with_items: ec2.tagged_instances

- name: wait for ssh to be available
  wait_for:
    host="{{ item.public_ip }}"
    port=22
  with_items: ec2.tagged_instances
